{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mikelward.androidlog",
    "module": "logging-android",
    "version": "2.0.66",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mikelward.androidlog",
          "module": "logging-core",
          "version": {
            "requires": "2.0.66"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "logging-android-2.0.66.aar",
          "url": "logging-android-2.0.66.aar",
          "size": 52106,
          "sha512": "5eabdab742180a613fd96b8ab9c392411208e703a0150dcc91388ce43801d35b328b12ed08c0cf877144fbd01a3bdd559edd6c6cfac336dd3d127a5c986fd805",
          "sha256": "cac9a9af1917a7125d18a77f94b6021ad255c69e0d256b2aa86fad466660daf2",
          "sha1": "e407d09d72bcab340a247994ec22262172d37f41",
          "md5": "2d87d86ec361eef739d28ea1f76875d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mikelward.androidlog",
          "module": "logging-core",
          "version": {
            "requires": "2.0.66"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "logging-android-2.0.66.aar",
          "url": "logging-android-2.0.66.aar",
          "size": 52106,
          "sha512": "5eabdab742180a613fd96b8ab9c392411208e703a0150dcc91388ce43801d35b328b12ed08c0cf877144fbd01a3bdd559edd6c6cfac336dd3d127a5c986fd805",
          "sha256": "cac9a9af1917a7125d18a77f94b6021ad255c69e0d256b2aa86fad466660daf2",
          "sha1": "e407d09d72bcab340a247994ec22262172d37f41",
          "md5": "2d87d86ec361eef739d28ea1f76875d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-android-2.0.66-sources.jar",
          "url": "logging-android-2.0.66-sources.jar",
          "size": 46342,
          "sha512": "8d9e3444eff7f25463d9557c2e9d30846ca2e7e009ba49cfa07af6bd9fcd07fe600d2b4a92ccb8739df3f22a69c3994341624937c6c2e89d290ac712cc029a15",
          "sha256": "f3c168a685a60a75241f0857c6670fcf364657693140d205482b082ef2e0b718",
          "sha1": "0ab926b06311c085a01dc2343978ec5fea1c4cc8",
          "md5": "cc1284fe18e654ba8198def6fd96dea6"
        }
      ]
    }
  ]
}
