{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mikelward.androidlog",
    "module": "logging-core",
    "version": "2.0.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-core-2.0.57.jar",
          "url": "logging-core-2.0.57.jar",
          "size": 36720,
          "sha512": "3f46a533a254c101d5c548ca3a2a7488a3b72f7552eee17bd4e7213570ab450f97931d54ff04f98a7a7e20146423c767623d4544c13684d57d4b9c252d096238",
          "sha256": "be97c21063aa252d42d68ce1912a142c93e92d95af1c3307f8a3c4ed5aa5e900",
          "sha1": "79b4da61008e1c879285dce7ac0e61e0025f4555",
          "md5": "cf13c990522a464b9d213e713fe51ff3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-core-2.0.57.jar",
          "url": "logging-core-2.0.57.jar",
          "size": 36720,
          "sha512": "3f46a533a254c101d5c548ca3a2a7488a3b72f7552eee17bd4e7213570ab450f97931d54ff04f98a7a7e20146423c767623d4544c13684d57d4b9c252d096238",
          "sha256": "be97c21063aa252d42d68ce1912a142c93e92d95af1c3307f8a3c4ed5aa5e900",
          "sha1": "79b4da61008e1c879285dce7ac0e61e0025f4555",
          "md5": "cf13c990522a464b9d213e713fe51ff3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-core-2.0.57-sources.jar",
          "url": "logging-core-2.0.57-sources.jar",
          "size": 36004,
          "sha512": "28dc879e84edca08793f9dee351486a99c247b85fab41b326d5074a0d1c94e45636ea0d7f974c44ada1f069f5b114b894f0cd8e4eb00d700468639fdc07ca450",
          "sha256": "c05610646c50b4a4f1c92e8fc4878045ec6ef290fd8ebbccf9f3a695f7052898",
          "sha1": "62693e43d5733d0c2cce2161bd3fed81e9f9465f",
          "md5": "73ed078fb774ffef637f332e05339f80"
        }
      ]
    }
  ]
}
